-- ============================================================
-- Auto-generated migration  2026-03-02
-- Generated by: scripts/sync-migrations.mjs
-- ============================================================

-- QuestionType (questions.question_type): +multichoice
ALTER TABLE questions DROP CONSTRAINT IF EXISTS questions_question_type_check;
ALTER TABLE questions ADD CONSTRAINT questions_question_type_check
  CHECK (question_type IN ('binary', 'rank', 'scale', 'string', 'multichoice'));

-- AnswerType (answers.answer_type): +multichoice
ALTER TABLE answers DROP CONSTRAINT IF EXISTS answers_answer_type_check;
ALTER TABLE answers ADD CONSTRAINT answers_answer_type_check
  CHECK (answer_type IN ('binary', 'rank', 'scale', 'string', 'multichoice'));

-- answer_type_matches_value: +multichoice
ALTER TABLE answers DROP CONSTRAINT IF EXISTS answer_type_matches_value;
ALTER TABLE answers ADD CONSTRAINT answer_type_matches_value CHECK (
    (answer_type = 'binary' AND binary_value IS NOT NULL) OR
    (answer_type = 'rank' AND rank_value IS NOT NULL) OR
    (answer_type = 'scale' AND scale_value IS NOT NULL) OR
    (answer_type = 'string' AND string_value IS NOT NULL) OR
    (answer_type = 'multichoice' AND string_value IS NOT NULL)
);
